openapi: 3.0.3
components:
  examples:
    inprogress:
      summary: In progress upload example
      value:
        upload_id: KrFTuglD.N8ireqry_w3.oQqNwrYI7SfSXpVRiusKah0YigDnuM06hfJNIUZg4R_No0MMW9FLU2UG5anTW0boTUYVxKfBZWCFXqnQTpjnQEo1K7la39MYpjSTvIbZgnG
        status: in-progress
        number_parts: 1
        urls:
        - url: https://data.geo.admin.ch/ch.swisstopo.pixelkarte-farbe-pk50.noscale/smr200-200-4-2019/smr50-263-2016-2056-kgrs-2.5.tiff
          part: 1
          expires: '2019-08-24T14:15:22Z'
        created: '2019-08-24T14:15:22Z'
        file:multihash: 12200ADEC47F803A8CF1055ED36750B3BA573C79A3AF7DA6D6F5A2AED03EA16AF3BC
    completed:
      summary: Completed upload example
      value:
        upload_id: KrFTuglD.N8ireqry_w3.oQqNwrYI7SfSXpVRiusKah0YigDnuM06hfJNIUZg4R_No0MMW9FLU2UG5anTW0boTUYVxKfBZWCFXqnQTpjnQEo1K7la39MYpjSTvIbZgnG
        status: completed
        number_parts: 1
        created: '2019-08-24T14:15:22Z'
        completed: '2019-08-24T14:15:22Z'
        file:multihash: 12200ADEC47F803A8CF1055ED36750B3BA573C79A3AF7DA6D6F5A2AED03EA16AF3BC
    aborted:
      summary: Aborted upload example
      value:
        upload_id: KrFTuglD.N8ireqry_w3.oQqNwrYI7SfSXpVRiusKah0YigDnuM06hfJNIUZg4R_No0MMW9FLU2UG5anTW0boTUYVxKfBZWCFXqnQTpjnQEo1K7la39MYpjSTvIbZgnG
        status: completed
        number_parts: 1
        created: '2019-08-24T14:15:22Z'
        aborted: '2019-08-24T14:15:22Z'
        file:multihash: 12200ADEC47F803A8CF1055ED36750B3BA573C79A3AF7DA6D6F5A2AED03EA16AF3BC
